name: Glitch Sync (Path Demo)

# Triggered when code is pushed to any branch in a repository
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use local glitch-sync
        uses: ./../../glitch-sync/glitch-sync
        with:
          project-id: '${{ secrets.SANDBOX_PROJECTID }}'
          auth-token: '${{ secrets.SANDBOX_AUTHTOKEN }}'
          path: 'demo' # sync demo folder
